### PR TITLE
Use Timo's sha2 library

### PR DESCRIPTION
**Pull request by chenyan2002**
Perf improved by 70%! See https://github.com/dfinity/canister-profiling/pull/73

### CODE REVIEW

**Comment by nomeata** [comment]
Looks like mops needs to be installed in the GitHub action.

**Comment by nomeata** [comment]
I tried to make a release, but couldn’t:
```
~/dfinity/ic-certification $ mops publish
Publishing ic-certification@0.1.2 [:         ]
Error: Dev Dependency matchers@ not found in registry
```

How do I proceed?

**Comment by chenyan-dfinity** [comment]
Can you retry by upgrading mops, `npm i -g ic-mops`?

**Comment by nomeata** [comment]
Now on
```
$ mops --version
CLI 0.22.0
API 1.2
```
but next problem is that the latest(?) SDK (0.14.3) ships `moc-0.9.3`, while it seems you need `0.9.7`, and then I get
```
~/dfinity/ic-certification $ mops publish
Error: Skipping /home/jojo/dfinity/ic-certification/src/ReqData.mo:
/home/jojo/dfinity/ic-certification/src/ReqData.mo:69.20-69.21: syntax error [M0001], unexpected token '>', expected one of token or <phrase> sequence:
  <exp_bin(ob)>
```

It probably makes sense to wait for 0.9.7 to be published with the SDK before releasing this?

**Comment by chenyan2002** [comment]
I see. `DFX_VERSION=0.15.0-beta.1 sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)"` contains 0.9.7. We can also wait until 0.15.0 becomes official.

**Comment by nomeata** [comment]
I'm using the nix setup to get dfx and mops, of course :-)

**Pull request merged**
